### ISSUE TITLE
WebML WG Hybrid Meeting at TPAC 2024

### ISSUE THREAD

**Issue by reillyeon** [webmachinelearning/meetings#23]
Given the increased participation in the group I think it would be appropriate to hold a hybrid meeting at TPAC 2024 in Anaheim, CA.

**Comment by anssiko** [comment]
Thank you for your feedback and responses to this indicative TPAC meeting poll. 👍

I have submitted a request to the TPAC 2024 meeting planners indicating the WebML WG's preference to meet during the TPAC meetings week. I will share more information including specific timing when the schedule is confirmed.

**Comment by anssiko** [comment]
The WebML WG will meet F2F on Monday, 23 September 2024, 09:00–18:00 PDT.

Announcement: https://lists.w3.org/Archives/Public/public-webmachinelearning-wg/2024Jun/0003.html

**Comment by anssiko** [comment]
As announced earlier, we'll meet F2F at TPAC and a work in progress draft agenda for the WebML WG meeting has been made available at https://github.com/webmachinelearning/meetings/issues/25

I'll close this indicative poll issue. Thank you for your interest and support that make this meeting a success.
