### ISSUE TITLE
Teleconference scheduling

### ISSUE THREAD

**Issue by anssiko** [webmachinelearning/meetings#3]
Let's use this meta issue to capture preference for teleconferences.

If you'd be interested in a monthly call (30 minutes), please add your current UTC timezone offset to this issue to help meeting scheduling.

I'll start with mine, UTC +2.

**Comment by gregwhitworth** [comment]
Might I recommend using Doodle, as it allows a little bit more granularity than UTC, although mine is UTC-7

https://doodle.com/poll/3cf4f8a6atnwdtca

The doodle is just for finding times that work for everyone - we can discuss which day of the month works best later.

**Comment by anssiko** [comment]
Current status of the doodle poll for a monthly WebML CG call is a tie between:

* [Thursdays 1:30-2:00pm UTC+0](https://www.timeanddate.com/worldclock/fixedtime.html?hour=13&min=30&sec=0&p1=0)
* [Thursdays 2:30-3:00pm UTC+0](https://www.timeanddate.com/worldclock/fixedtime.html?hour=14&min=30&sec=0&p1=0)

The later slot would better accommodate possible early birds from US/Pacific, so I'm leaning toward it especially if we get more signals from that direction. The balancing act is to keep the time reasonable for our active PRC and Japan participants who seem to be very flexible with timing already.

All - please respond to the poll by this Friday 2018-11-09:

https://doodle.com/poll/3cf4f8a6atnwdtca

Already responded: @huningxin @tomoyukilabs @RafaelCintron @jawache @kdavis-mozilla @anssiko @gregwhitworth (thanks!)

**Comment by anssiko** [comment]
The most popular slot is:

* [Thursdays 2:30-3:00pm UTC+0](https://www.timeanddate.com/worldclock/fixedtime.html?hour=14&min=30&sec=0&p1=0)

The (shared) second most popular slot that'd accommodate Dean @grorg and Myles @litherum from Apple and Rafael @RafaelCintron from Microsoft is:

* [Thursdays 6:00-6:30pm UTC+0](https://www.timeanddate.com/worldclock/fixedtime.html?hour=18&min=00&sec=0&p1=0)

Since we're still expecting new participants from more companies, I'd like to keep the poll open for a little longer.

**Comment by zixia** [comment]
Hello, I'm interested in joining the monthly call.

My UTC is +8, Beijing, and I always work in the midnight and sleep in the morning... :P

**Comment by zixia** [comment]
@anssiko Thanks for the welcome, and I had already joined the awesome W3C Web ML Group and posted my hours on the doodle.

**Comment by gregwhitworth** [comment]
@anssiko We're now at about 3 weeks since this began. Maybe we should book the second Thursday of every month starting on December 13th 6:00-6:30pm UTC+0? That gives us ~3.5 weeks to build up an agenda and get the telecon info distributed. Thoughts everyone?

**Comment by anssiko** [comment]
Let’s aim for Dec 13th start. Thursdays 2:30-3:00pm UTC+0 seem the most popular vote with a widening gap (8 vs. 6) so I’d lean toward it instead. Going forward, we can try rotate between the two slots to get wider participation. Hoping that’s a reasonable compromise.

I’ll send a mail with meeting details once I’ve confirmed the logistics.

Proposals for telecon agenda topics can be dropped here already. I’ve recorded two proposals:

* High level vs low level  https://github.com/webmachinelearning/webnn/issues/3

* Use cases https://github.com/webmachinelearning/webnn/pull/2

Optimally we’d have landed our first stab at use cases by telecon and would discuss further refinements.

**Comment by anssiko** [comment]
I've reserved us the following two slots that we will alternate depending on topics and expected participants:

* [Thursdays 2:30-3:00pm UTC+0](https://www.timeanddate.com/worldclock/fixedtime.html?hour=14&min=30&sec=0&p1=0)
* [Thursdays 6:00-6:30pm UTC+0](https://www.timeanddate.com/worldclock/fixedtime.html?hour=18&min=00&sec=0&p1=0)

The first teleconference will be held 13 December 2018, 14:30-15:00 UTC+0:
https://github.com/webmachinelearning/meetings/blob/master/telcons/2018-12-13-agenda.md

Also announced on the mailing list:
https://lists.w3.org/Archives/Public/public-webmachinelearning/2018Nov/0004.html

(Closing this issue since we resolved scheduling. Further feedback on agenda topics please send to the mailing list.)
